# Generated by Django 4.2.5 on 2023-09-14 00:51

import core.main.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_end_date_alter_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=500, validators=[core.main.validations.no_special_characters]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, validators=[core.main.validations.no_special_characters]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, validators=[core.main.validations.no_special_characters]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, validators=[core.main.validations.no_special_characters]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500, validators=[core.main.validations.no_special_characters]),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, validators=[core.main.validations.no_special_characters]),
        ),
    ]
