# Generated by Django 4.2.5 on 2023-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_groupmembership_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
